# Config file to control analysis params for PhD thesis.


## Train period set to be 1 full year, so at least a possibility of learning seasonal patterns
train_start: "1996-03-26T23:00:00+00" # Rounded UTC time of earliest FM field observation
train_end: "1997-03-26T23:00:00+00" # One year from train start
## Val and Test/Forecast periods split remaining times
val_start: "1997-03-27T00:00:00+00"
val_end: "1997-08-13T11:00:00+00"
f_start: "1997-08-13T12:00:00+00"
f_end: "1997-12-30T22:00:00+00"




